### ISSUE TITLE
Allow users to designate their own repositories rather than defaults.

### ISSUE THREAD

**Issue by candyfodder** [Trol1337/LibraryManager#1]
Hey Trol,
Looks great so far other than a few mishaps. If you don't mind, allowing users to designate their own repos via a register function or so would work great. My recommendation would be to store the repos in their own map as values and then grab them by key (The title of the repo). Also focusing this for Minecraft might be not such a great idea. Otherwise, keep up the great work.

Thanks,
Kix

**Comment by Trol1337** [comment]
I got a suggestion 5 minutes after I posted to the the clirnt guys discord, that I should make an interface called repository, and the end user, which in this case is you, will make the all repositories they'll use tin the future.

**Comment by Trol1337** [comment]
Added, thank you for the suggestion!
